require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable
  Exclude:
    - vendor/**/*
    - test/**/*.rb
    - db/migrate/*.rb
    - bin/*
    - db/schema.rb
    - db/seeds.rb
    - config/environments/**/*.rb
    - config/application.rb

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 180

# TODO: Lower that number !
Metrics/AbcSize:
  Max: 24

# TODO: Lower that number !
Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 25
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Max: 10

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5

Style/OpenStructUse:
  Enabled: false