#!/usr/bin/env ruby
# frozen_string_literal: true

system("git remote update > /dev/null 2>&1")
outdated = `git status -uno`.include?("Your branch is behind")

if outdated
  puts "Starting update at #{Time.zone.now}"
  system("git pull")
  system("bundle install")
  system("RAILS_ENV=production bundle exec rails db:migrate")
  system("yarn install")
  system("RAILS_ENV=production bundle exec rails assets:precompile")
  system("sudo service nginx restart")
  system("sudo service sidekiq restart")
  puts "Finishing update at #{Time.zone.now}"
end
